version: "3.9"

services:
  mycassandra-dc1node1:
    image: cassandra:latest
    container_name: mycassandra-dc1node1
    hostname: mycassandra-dc1node1
    networks:
      dcnet:
        ipv4_address: 172.30.1.1
    ports:
      - "9042:9042"
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_CLUSTER_NAME=myclustercassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch      
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=dc1rack1
      - CASSANDRA_SEEDS=mycassandra-dc1node2,mycassandra-dc1node3,mycassandra-dc2node1
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: on-failure:5
    volumes:
      - my-cassandra-dc1n1_data:/var/lib/cassandra

  mycassandra-dc1node2:
    image: cassandra:latest
    container_name: mycassandra-dc1node2
    hostname: mycassandra-dc1node2
    networks:
      dcnet:
        ipv4_address: 172.30.1.2
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_CLUSTER_NAME=myclustercassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch      
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=dc1rack1
      - CASSANDRA_SEEDS=mycassandra-dc1node1,mycassandra-dc2node1
    depends_on:
      - mycassandra-dc1node1
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: on-failure:5
    volumes:
      - my-cassandra-dc1n2_data:/var/lib/cassandra

  mycassandra-dc1node3:
    image: cassandra:latest
    container_name: mycassandra-dc1node3
    hostname: mycassandra-dc1node3
    networks:
      dcnet:
        ipv4_address: 172.30.1.3
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_CLUSTER_NAME=myclustercassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch      
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=dc1rack1
      - CASSANDRA_SEEDS=mycassandra-dc1node1,mycassandra-dc1node2,mycassandra-dc2node1
    depends_on:
      - mycassandra-dc1node2
      - mycassandra-dc1node1
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: on-failure:5
    volumes:
      - my-cassandra-dc1n3_data:/var/lib/cassandra

  mycassandra-dc1node4:
    image: cassandra:latest
    container_name: mycassandra-dc1node4
    hostname: mycassandra-dc1node4
    networks:
      dcnet:
        ipv4_address: 172.30.1.4
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_CLUSTER_NAME=myclustercassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch      
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=dc1rack1
      - CASSANDRA_SEEDS=mycassandra-dc1node1,mycassandra-dc1node2,mycassandra-dc2node1
    depends_on:
      - mycassandra-dc1node3
      - mycassandra-dc1node2
      - mycassandra-dc1node1
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: on-failure:5
    volumes:
      - my-cassandra-dc1n4_data:/var/lib/cassandra

  mycassandra-dc2node1:
    image: cassandra:latest
    container_name: mycassandra-dc2node1
    hostname: mycassandra-dc2node1
    networks:
      dcnet:
        ipv4_address: 172.30.2.1
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_CLUSTER_NAME=myclustercassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch      
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=dc2rack1
      - CASSANDRA_SEEDS=mycassandra-dc1node1
    depends_on:
      - mycassandra-dc1node1
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: on-failure:5
    volumes:
      - my-cassandra-dc2n1_data:/var/lib/cassandra

  mycassandra-dc2node2:
    image: cassandra:latest
    container_name: mycassandra-dc2node2
    hostname: mycassandra-dc2node2
    networks:
      dcnet:
        ipv4_address: 172.30.2.2
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_CLUSTER_NAME=myclustercassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch      
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=dc2rack1      
      - CASSANDRA_SEEDS=mycassandra-dc1node1,mycassandra-dc2node1
    depends_on:
      - mycassandra-dc1node1
      - mycassandra-dc1node2
      - mycassandra-dc2node1
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: on-failure:5
    volumes:
      - my-cassandra-dc2n2_data:/var/lib/cassandra

  mycassandra-dc2node3:
    image: cassandra:latest
    container_name: mycassandra-dc2node3
    hostname: mycassandra-dc2node3
    networks:
      dcnet:
        ipv4_address: 172.30.2.3
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_CLUSTER_NAME=myclustercassandra
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch      
      - CASSANDRA_DC=DC2
      - CASSANDRA_RACK=dc2rack1      
      - CASSANDRA_SEEDS=mycassandra-dc2node1,mycassandra-dc2node2,mycassandra-dc1node1
    depends_on:      
      - mycassandra-dc1node1
      - mycassandra-dc1node2
      - mycassandra-dc2node1
      - mycassandra-dc2node2
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: on-failure:5
    volumes:
      - my-cassandra-dc2n3_data:/var/lib/cassandra

volumes:
  my-cassandra-dc1n1_data:
    driver: local
  my-cassandra-dc1n2_data:
    driver: local
  my-cassandra-dc1n3_data:
    driver: local
  my-cassandra-dc1n4_data:
    driver: local
  my-cassandra-dc2n1_data:
    driver: local
  my-cassandra-dc2n2_data:
    driver: local
  my-cassandra-dc2n3_data:
    driver: local

networks:
    dcnet:
      ipam:
        driver: default
        config:
          - subnet: 172.30.0.0/16